--Tarea 1 unidad 2--
USE Northwind
GO
--1--
SELECT FIRSTNAME AS NOMBRE, LASTNAME AS APELLIDO
FROM EMPLOYEES
GO
       
--2--
SELECT *
FROM EMPLOYEES
WHERE DATEDIFF(YEAR, BIRTHDATE, HIREDATE) BETWEEN 30 AND 50

--3--
Select FirstName+ ' '+ LastName + ' ENTRO A TRABAJAR UN '+ DATENAME(dw, HireDate) + ' '+
DATENAME(dd, HireDate)+ ' DE '+ DATENAME(mm,HireDate) + ' DE ' + CONVERT(Char(5), DatePart(yy, HireDate)) 
+ ' CON UNA EDAD DE '+ Convert(Char(5), DateDiff(yy, BirthDate, HireDate)) + 'AÑOS '
From Employees

SELECT UPPER(FIRSTNAME+ ' '+ LASTNAME + ' ENTRO A TRABAJAR UN '+ DATENAME(DW, HIREDATE) + ' '+ DATENAME(DD, HIREDATE)+ ' DE '+ DATENAME(MM,HIREDATE) + ' DE ' + CONVERT(CHAR(5), DATEPART(YY, HIREDATE))+ ' CON UNA EDAD DE '+ CONVERT(CHAR(5), DATEDIFF(YY, BIRTHDATE, HIREDATE)) + 'AÑOS ')
FROM EMPLOYEES

--4--
SELECT ORDERID, ORDERDATE
FROM ORDERS
WHERE DATEPART(DW, ORDERDATE) = 2 AND DATEPART(MM, ORDERDATE) BETWEEN 1 AND 6
ORDER BY ORDERID

--5--
SELECT O.ORDERID, O.ORDERDATE
FROM ORDERS O
INNER JOIN EMPLOYEES E ON O.EMPLOYEEID = E.EMPLOYEEID
WHERE DATEPART(DW, O.ORDERDATE) = 6 AND E.EMPLOYEEID IN (1, 3, 5)
ORDER BY O.ORDERID

--6--
SELECT
    CONCAT(
        'la orden ', O.ORDERID, ' ',
        'fue realizada por el cliente ', UPPER(C.CONTACTNAME), ' ',
        'y atendida por el empleado ', E.EMPLOYEEID
    ) AS InformacionOrden
FROM ORDERS O
INNER JOIN EMPLOYEES E ON O.EMPLOYEEID = E.EMPLOYEEID
INNER JOIN CUSTOMERS C ON O.CUSTOMERID = C.CUSTOMERID

--7--
SELECT CUSTOMERID, CONTACTNAME
FROM CUSTOMERS 
WHERE CONTACTNAME LIKE '[^aeiou]%' AND LEN(CONTACTNAME) > 10

--8--
SELECT *
FROM PRODUCTS
WHERE PRODUCTNAME LIKE '[ABN]%N'
--9--
SELECT FIRSTNAME, LASTNAME
FROM EMPLOYEES
WHERE FIRSTNAME LIKE '%[^AEIOU]' AND LASTNAME LIKE '%[^AEIOU]'

--10--
SELECT *
FROM ORDERS
WHERE DATENAME(MM, ORDERDATE) LIKE '[aeiou]%'
--11--
SELECT PRODUCTID, PRODUCTNAME
FROM PRODUCTS
WHERE PRODUCTNAME LIKE '%[AEIOU]%[AEIOU]%[AEIOU]%' AND PRODUCTNAME NOT LIKE '%[AEIOU]%[AEIOU]%[AEIOU]%[AEIOU]%'

--12--
SELECT *
FROM ORDERS
WHERE DATEPART(YY, ORDERDATE) % 3 = 0

--13--
SELECT *
FROM ORDERS O
WHERE (DATEPART(DW, O.ORDERDATE) = 1 OR -- DOMINGO 
	   DATEPART(DW, O.ORDERDATE) = 7 -- SABADO
	  ) 
	   AND EMPLOYEEID IN (1,2,5)
--14--
Select *
From Orders 
Where ShipVia is null or Datepart(mm, Orderdate) = 1 

--15--
SELECT TOP 10 *
FROM ORDERS
WHERE DATEPART(YY, ORDERDATE) = 1997
ORDER BY ORDERDATE DESC
--16--
SELECT TOP 10 *
FROM PRODUCTS
WHERE SUPPLIERID IN (1, 2, 5)
ORDER BY UNITPRICE DESC

--17--
SELECT TOP 4 *
FROM EMPLOYEES
ORDER BY (HIREDATE) ASC

--18--
SELECT *
FROM EMPLOYEES
WHERE(DATEDIFF(YEAR, BIRTHDATE, HIREDATE) IN (10, 20, 30) AND DATEDIFF(YEAR, BIRTHDATE, GETDATE()) > 30) OR (ADDRESS IS NOT NULL AND REGION IS NULL)
--19--
SELECT *
FROM ORDERS
WHERE SHIPPOSTALCODE NOT LIKE '%[^a-zA-Z]%'
--20--
SELECT *
FROM ORDERS
WHERE DATEPART(YEAR, ORDERDATE) = 1996 AND DATENAME(MONTH, ORDERDATE) LIKE '%R%'


select * from Employees




--Tarea 2 unidad 2--
SELECT EMPLOYEES.FIRSTNAME + ' ' + EMPLOYEES.LASTNAME AS 'NOMBRE DEL EMPLEADO', 
    TERRITORIES.TERRITORYDESCRIPTION AS 'NOMBRE DEL TERRITORIO'
FROM EMPLOYEES 
INNER JOIN EMPLOYEETERRITORIES ON EMPLOYEES.EMPLOYEEID = EMPLOYEETERRITORIES.EMPLOYEEID
INNER JOIN TERRITORIES ON EMPLOYEETERRITORIES.TERRITORYID = TERRITORIES.TERRITORYID
WHERE (EMPLOYEES.FIRSTNAME + ' ' + EMPLOYEES.LASTNAME) LIKE '[AEIOU]%[AEIOU]' AND
    TERRITORIES.TERRITORYDESCRIPTION LIKE '[AEIOU]%[AEIOU]'


--7--
SELECT ORDERS.ORDERID AS 'FOLIO DE LA ORDEN', 
    DATEDIFF(MONTH, ORDERS.ORDERDATE, GETDATE()) AS 'MESES TRANSCURRIDOS DE LA ORDEN', 
    EMPLOYEES.FIRSTNAME + ' ' + EMPLOYEES.LASTNAME AS 'NOMBRE DEL EMPLEADO'
FROM ORDERS 
INNER JOIN EMPLOYEES ON ORDERS.EMPLOYEEID = EMPLOYEES.EMPLOYEEID
WHERE EMPLOYEES.COUNTRY = 'USA' AND EMPLOYEES.POSTALCODE LIKE '%2%'

--8--
SELECT ORDERS.ORDERID AS 'FOLIO DE LA ORDEN', 
    PRODUCTS.PRODUCTNAME AS 'NOMBRE DEL PRODUCTO', 
    [Order Details].UNITPRICE * [Order Details].QUANTITY AS 'IMPORTE DE VENTA'
FROM 
    ORDERS 
INNER JOIN [Order Details] ON ORDERS.ORDERID = [Order Details].ORDERID
INNER JOIN PRODUCTS ON [Order Details].PRODUCTID = PRODUCTS.PRODUCTID
INNER JOIN CATEGORIES ON PRODUCTS.CATEGORYID = CATEGORIES.CATEGORYID
WHERE CATEGORIES.CATEGORYNAME LIKE '%[AEIOU][AEIOU]%' OR CATEGORIES.CATEGORYNAME LIKE '_%[^AEIOU]'

--9--
SELECT EMPLOYEES.FIRSTNAME + ' ' + EMPLOYEES.LASTNAME AS 'NOMBRE DEL EMPLEADO',
	TERRITORIES.TERRITORYDESCRIPTION AS 'TERRITORIO'
FROM EMPLOYEES 
INNER JOIN EMPLOYEETERRITORIES ON EMPLOYEES.EMPLOYEEID = EMPLOYEETERRITORIES.EMPLOYEEID
INNER JOIN TERRITORIES ON EMPLOYEETERRITORIES.TERRITORYID = TERRITORIES.TERRITORYID
INNER JOIN REGION ON TERRITORIES.REGIONID = REGION.REGIONID
WHERE SUBSTRING(REGION.REGIONDESCRIPTION, 2, 1) = 'O'

SELECT E.FIRSTNAME AS 'NOMBRE DEL EMPLEADO', 
       T.TERRITORYDESCRIPTION AS 'TERRITORIO'
FROM EMPLOYEES E
INNER JOIN EMPLOYEETERRITORIES ET ON E.EMPLOYEEID = ET.EMPLOYEEID
INNER JOIN TERRITORIES T ON ET.TERRITORYID = T.TERRITORYID
INNER JOIN REGION R ON T.REGIONID = R.REGIONID
WHERE R.REGIONDESCRIPTION LIKE '_O%'


--10--
SELECT ORDERS.ORDERID AS 'FOLIO DE LA ORDEN', 
    ORDERS.ORDERDATE AS 'FECHA DE LA ORDEN', 
    EMPLOYEES.FIRSTNAME + ' ' + EMPLOYEES.LASTNAME AS 'NOMBRE DEL EMPLEADO',
    DATEDIFF(YEAR, EMPLOYEES.BIRTHDATE, ORDERS.ORDERDATE) AS 'EDAD DEL EMPLEADO AL HACER LA ORDEN'
FROM ORDERS 
INNER JOIN EMPLOYEES ON ORDERS.EMPLOYEEID = EMPLOYEES.EMPLOYEEID

