USE CONGRESO
GO
--VIEW 1
CREATE VIEW VW_EVENTOS AS
SELECT EV.EVEID, EV.EVENOMBRE, EV.EVEFECHA, EV.EVELUGAR, EV.EVECOSTO,
EX.EXPID, EX.EXPNOMBRE, EX.EXPAPELLIDOS, EX.EXPCORREO, EX.EXPCELULAR
FROM EVENTOS EV
INNER JOIN EXPOSITORES EX ON EV.EXPID = EX.EXPID

--VIEW 2
CREATE VIEW VW_REGISTROS AS
SELECT
    -- REGISTROS
    R.FOLIO, R.FECHA,
    -- CONGRESOS
    C.CONID, C.CONNOMBRE, C.CONDESCRIPCION, C.CONFECHAINI, C.CONFECHAFIN, C.CONLUGAR,
    -- VIEW 3
    E.*
FROM REGISTROS R
INNER JOIN CONGRESOS C ON R.CONID = C.CONID
INNER JOIN ESTUDIANTES E ON R.ESTID = E.ESCID
GO
--VIEW 3
CREATE VIEW VW_ESTUDIANTES AS
SELECT
    -- ESTUDIANTE
    E.ESTID, E.ESTNOMBRE, E.ESTAPELLIDOS, E.ESTDOMICILIO, E.ESTCORREO, E.ESTCELULAR,
    -- ESCUELA
    S.ESCID, S.ESCNOMBRE, S.ESCDOMICILIO,
    -- MUNICIPIO
    M.MUNID, M.MUNNOMBRE
FROM ESTUDIANTES E
INNER JOIN ESCUELAS S ON E.ESCID = S.ESCID
INNER JOIN MUNICIPIOS M ON S.MUNID = M.MUNID
GO
--VIEW 4
CREATE VIEW VW_EVETOXREGISTRO AS
SELECT 
E.*,
VR.*
FROM EVENTOXREG EXR
INNER JOIN EVENTOS E ON EXR.EVEID = E.EVEID
INNER JOIN VW_REGISTROS VR ON VR.FOLIO = EXR.FOLIO

DROP VIEW VW_REGISTROS
DROP VIEW VW_ESTUDIANTES
DROP VIEW VW_EVENTOS
DROP VIEW VW_EVETOXREGISTRO
